# Generated by Django 2.2.8 on 2019-12-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrocompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
